# Simple Node.js CI
# This workflow will install dependencies and run basic checks
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run build (if available)
        run: npm run build || echo "No build script defined"
      - name: Run tests (if available)
        run: npm test || echo "No test script defined"
